# Generated by Django 3.0.14 on 2024-10-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=12)),
                ('cpf', models.CharField(max_length=12, unique=True)),
                ('date_birth', models.DateField()),
            ],
        ),
    ]
