# Generated by Django 3.0.14 on 2024-10-16 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_product', models.CharField(max_length=100, unique=True)),
                ('name_product', models.CharField(max_length=100)),
                ('price_product', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_order', models.CharField(max_length=100, unique=True)),
                ('date_order', models.DateField()),
                ('total_order', models.DecimalField(decimal_places=2, max_digits=8)),
                ('code_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Shop.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Orderitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_product', models.IntegerField()),
                ('code_order', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Shop.Orders')),
                ('code_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Shop.Products')),
            ],
        ),
    ]
